// <auto-generated />
using System;
using LibrarySystem.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LibrarySystem.Api.Migrations
{
    [DbContext(typeof(LibraryDbContext))]
    [Migration("20260509211618_UpdateSeedDataWithNewFieldNames")]
    partial class UpdateSeedDataWithNewFieldNames
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.7");

            modelBuilder.Entity("LibrarySystem.Api.Entities.Book", b =>
                {
                    b.Property<int>("InventoryNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsBorrowed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Publisher")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ReleaseYear")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("InventoryNumber");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            InventoryNumber = 1,
                            Author = "Molnár Ferenc",
                            IsBorrowed = false,
                            Publisher = "Móra",
                            ReleaseYear = 1907,
                            Title = "A Pál utcai fiúk"
                        },
                        new
                        {
                            InventoryNumber = 2,
                            Author = "Gárdonyi Géza",
                            IsBorrowed = false,
                            Publisher = "Dante",
                            ReleaseYear = 1901,
                            Title = "Egri csillagok"
                        },
                        new
                        {
                            InventoryNumber = 3,
                            Author = "Robert C. Martin",
                            IsBorrowed = false,
                            Publisher = "Prentice Hall",
                            ReleaseYear = 2008,
                            Title = "Clean Code"
                        });
                });

            modelBuilder.Entity("LibrarySystem.Api.Entities.Loan", b =>
                {
                    b.Property<int>("LoanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BookInventoryNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BookNumber")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LoanDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("ReaderNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ReaderNumber1")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ReturnDeadline")
                        .HasColumnType("TEXT");

                    b.HasKey("LoanId");

                    b.HasIndex("BookInventoryNumber");

                    b.HasIndex("ReaderNumber1");

                    b.ToTable("Loans");
                });

            modelBuilder.Entity("LibrarySystem.Api.Entities.Reader", b =>
                {
                    b.Property<int>("ReaderNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ReaderNumber");

                    b.ToTable("Readers");

                    b.HasData(
                        new
                        {
                            ReaderNumber = 1,
                            Address = "4400 Nyíregyháza, Kossuth tér 1-3.",
                            DateOfBirth = new DateTime(1990, 4, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Tóth Tibor"
                        },
                        new
                        {
                            ReaderNumber = 2,
                            Address = "4024 Debrecen, Piac utca 20.",
                            DateOfBirth = new DateTime(2005, 9, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Takács Éva"
                        });
                });

            modelBuilder.Entity("LibrarySystem.Api.Entities.Loan", b =>
                {
                    b.HasOne("LibrarySystem.Api.Entities.Book", "Book")
                        .WithMany()
                        .HasForeignKey("BookInventoryNumber");

                    b.HasOne("LibrarySystem.Api.Entities.Reader", "Reader")
                        .WithMany()
                        .HasForeignKey("ReaderNumber1");

                    b.Navigation("Book");

                    b.Navigation("Reader");
                });
#pragma warning restore 612, 618
        }
    }
}
